name: Generate Snake Animation

on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Snake Animation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Snake animation generator
        run: pip install -U git+https://github.com/Platane/snk@master

      - name: Generate Snake animation
        run: snk --output dist/github-contribution-grid-snake.svg Eduardo-Camargo-Gomes

      - name: Deploy Snake animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
